packages:
  - playground
  - docs
  - packages/*
  - examples/*
catalog:
  '@antfu/eslint-config': ^4.13.1
  '@antfu/install-pkg': ^1.1.0
  '@antfu/ni': ^24.1.0
  '@antfu/utils': ^9.1.0
  '@clack/prompts': ^0.10.1
  '@eslint-react/eslint-plugin': ^1.49.0
  '@next/eslint-plugin-next': ^15.3.2
  '@types/eslint-plugin-tailwindcss': ^3.17.0
  '@types/node': ^22.13.10
  bumpp: ^10.1.0
  eslint: ^9.22.0
  eslint-plugin-format: ^1.0.1
  eslint-plugin-react-hooks: ^5.2.0
  eslint-plugin-react-refresh: ^0.4.20
  eslint-plugin-tailwindcss: ^3.18.0
  eslint-typegen: ^2.1.0
  lint-staged: ^15.5.0
  local-pkg: ^1.1.1
  simple-git-hooks: ^2.11.1
  tsdown: ^0.11.1
  tsx: ^4.19.3
  typescript: ^5.8.2
onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks
